In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('pcadata.csv')
df.head()

x   y
0   4  11
1   8   4
2  13   5
3   7  14

In [3]:
# Mean normalization
df = df - df.mean()
df.head()

x    y
0 -4.0  2.5
1  0.0 -4.5
2  5.0 -3.5
3 -1.0  5.5

In [4]:
# Covariance matrix of df
cov_mat = np.cov(df, rowvar=False)
cov_mat

array([[ 14., -11.],
       [-11.,  23.]])

In [5]:
# Eigenvalues and eigenvectors of the covariance matrix
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
print('Eigenvalues: \n', eig_vals)
print('\nEigenvectors: \n', eig_vecs)

Eigenvalues: 
 [ 6.61513568 30.38486432]

Eigenvectors: 
 [[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [6]:
# Feature vector
feature_vec = eig_vecs[0]
feature_vec

array([-0.83025082,  0.55738997])

In [7]:
# Normalize the feature vector and find pc1
feature_vec_norm = feature_vec / np.linalg.norm(feature_vec)
pc1 = np.dot(df, feature_vec_norm)
pc1

array([ 4.7144782 , -2.50825486, -6.10211899,  3.89589565])